class LessonItem {
  final String id;
  final String vietnamese;
  final String english;
  final String? audioUrl; // Can be generated by TTS if null

  const LessonItem({
    required this.id,
    required this.vietnamese,
    required this.english,
    this.audioUrl,
  });
}

class Lesson {
  final String id;
  final String title;
  final String description;
  final List<LessonItem> items;
  final int targetMastery;

  const Lesson({
    required this.id,
    required this.title,
    required this.description,
    required this.items,
    this.targetMastery = 3,
  });
}

class Level {
  final String id;
  final String title;
  final String description;
  final List<Lesson> lessons;

  const Level({
    required this.id,
    required this.title,
    required this.description,
    required this.lessons,
  });
}
